FROM node:20-alpine AS builder

WORKDIR /app

# Copy dependency definitions
COPY webui/package.json webui/yarn.lock webui/.yarnrc.yml ./
COPY webui/.yarn ./.yarn

# Install dependencies
RUN yarn install

# Copy the rest of the frontend source code
COPY webui/ .

# Build the application
RUN yarn build-prod

FROM nginx:alpine

# Copy built assets from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
